import type { DataTypeSchema } from "./types";

export const billingLogsSchema: DataTypeSchema = {
  dataType: "billing_logs",
  dbName: "prod",
  collection: "userplanhistories",
  customerField: "user",
  timestampField: "createdAt",
  filters: [
    { key: "planId", label: "Plan ID", type: "search" },
    { key: "planName", label: "Plan Name", type: "search" },
    { key: "planState", label: "Plan State", type: "select", options: ["ACTIVE", "INACTIVE", "UNKNOWN"] },
    { key: "isBusiness", label: "Business", type: "select", options: ["true", "false"] },
    { key: "expired", label: "Expired", type: "select", options: ["true", "false"] },
    { key: "deletedState", label: "Deleted State", type: "select", options: ["active", "deleted"] },
  ],
  columns: [
    { key: "createdAt", label: "시간", type: "datetime" },
    { key: "user", label: "User", type: "string" },
    { key: "isBusiness", label: "Business", type: "boolean" },
    { key: "planId", label: "Plan ID", type: "string" },
    { key: "planName", label: "Plan Name", type: "string" },
    { key: "planState", label: "Plan State", type: "string" },
    { key: "planPriceKRW", label: "Plan Price (KRW)", type: "number" },
    { key: "planPriceUSD", label: "Plan Price (USD)", type: "number" },
    { key: "planPriceJPY", label: "Plan Price (JPY)", type: "number" },
    { key: "discount", label: "Discount", type: "number" },
    { key: "paymentDate", label: "Payment Date", type: "datetime" },
    { key: "lastPaymentDate", label: "Last Payment Date", type: "datetime" },
    { key: "expiresAt", label: "Expires At", type: "datetime" },
    { key: "deletedAt", label: "Deleted At", type: "datetime" },
    { key: "expired", label: "Expired", type: "boolean" },
    { key: "expiredAt", label: "Expired At", type: "datetime" },
    { key: "usage", label: "Usage", type: "object" },
    { key: "normalizedUsage", label: "Normalized Usage", type: "object" },
    { key: "usageNormalizationStatus", label: "Usage Normalization Status", type: "string" },
  ],
};
